<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Record\**" />
    <EmbeddedResource Remove="Record\**" />
    <None Remove="Record\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.36" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
    <ProjectReference Include="..\Packages.Helpers.Application\Packages.Helpers.Application.csproj" />
    <ProjectReference Include="..\Packages.Queues.Application\Packages.Queues.Application.csproj" />
    <ProjectReference Include="..\Packages.WebSocket.Application\Packages.Ws.Application.csproj" />
  </ItemGroup>

</Project>
