<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Record\**" />
    <EmbeddedResource Remove="Record\**" />
    <None Remove="Record\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="6.0.36" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="6.0.36" />
    <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="6.35.1" />
    <PackageReference Include="Web.Api.Toolkit.Helpers.Application" Version="1.0.41" />
    <PackageReference Include="Web.Api.Toolkit.Identity.Application" Version="1.0.41" />
    <PackageReference Include="Web.Api.Toolkit.Ws.Application" Version="1.0.41" />
    <PackageReference Include="Ws.Application" Version="1.0.2" />
    <PackageReference Include="System.Threading.Tasks" Version="4.3.0" />
    <PackageReference Include="System.Diagnostics.Debug" Version="4.3.0" />
    <PackageReference Include="System.Runtime.InteropServices" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem.Primitives" Version="4.3.0" />
    <PackageReference Include="System.IO" Version="4.3.0" />
    <PackageReference Include="System.IO.FileSystem" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Domain\Domain.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

</Project>
